#!/bin/bash
# To use, put something like this in your .tmux.conf:
#     bind M-0 command-prompt -p Repository: 'run "~/bin/tmux-new-window.sh %1 0"'
 
PROJECT=$1
WINDOW=$2
 
PROJECT_DIR=~/$PROJECT
for DIR in $HOME /Volumes/git $HOME/bin  ; do
  if [ -d "$DIR/$PROJECT" ]; then
    PROJECT_DIR=$DIR/$PROJECT
  fi
done

cd $PROJECT_DIR
tmux new-window ${WINDOW:+-t$WINDOW} -n $PROJECT
if [ -d "$PROJECT_DIR/.git" -o -d "$PROJECT_DIR/../.git" ]; then
  tmux splitw -d  # Ensure kill-pane doesn't kill pane 0 (weird bug in -a)
  tmux kill-pane -a -t 0
  tmux splitw -d
  tmux splitw -d "source ~/.profile ; git graph-branch --watch"
  tmux splitw -d $HOME/bin/gittools/watch-status

  ~/bin/tmuxtools/chrislayout

  tmux respawn-pane -kt 0
  tmux clear-history -t 0
  tmux respawn-pane -kt 3
  tmux clear-history -t 3

else
  tmux split-window -hd
  ~/bin/tmuxtools/chrislayout
fi
