#!/bin/bash
WINDOW=$1
if tmux list-windows -F '#{window_index}' | grep -q "^${WINDOW}\$" ; then
  tmux select-window -t $WINDOW
else
  tmux command-prompt -p 'Repository:' "run '~/bin/tmuxtools/new-window %1 $WINDOW'"
fi
